<?php

use Illuminate\Database\Seeder;
use App\candy_antecedent;

class AntecedentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Familiar con Enfermedad Coronaria';   $candy_antecedent->tx_antecedent_category = '4';
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Familiar con Eccema';                 $candy_antecedent->tx_antecedent_category = '4';
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Familiar con Asma';                   $candy_antecedent->tx_antecedent_category = '4';
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Familiar con Cáncer';                 $candy_antecedent->tx_antecedent_category = 4;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Familiar con Rinitis Alergica';       $candy_antecedent->tx_antecedent_category = 4;
        $candy_antecedent->save();





        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Alcoholismo';                         $candy_antecedent->tx_antecedent_category = 1;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Sedentarismo';                        $candy_antecedent->tx_antecedent_category = 1;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Insomnio';                            $candy_antecedent->tx_antecedent_category = 1;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Fumador';                             $candy_antecedent->tx_antecedent_category = 1;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Adicción a Narcóticos';               $candy_antecedent->tx_antecedent_category = 1;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Obesidad';                            $candy_antecedent->tx_antecedent_category = 1;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Ingesta Excesiva de Alimentos';       $candy_antecedent->tx_antecedent_category = 1;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Mal manejo de la Ira';                $candy_antecedent->tx_antecedent_category = 1;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Alergia Alimenticia';                 $candy_antecedent->tx_antecedent_category = 2;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Alzheimer';                           $candy_antecedent->tx_antecedent_category = 2;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Amenorrea';                           $candy_antecedent->tx_antecedent_category = 2;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Anemia';                              $candy_antecedent->tx_antecedent_category = 2;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Anorexia';                            $candy_antecedent->tx_antecedent_category = 2;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Ansiedad';                            $candy_antecedent->tx_antecedent_category = 2;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Esquizofrenia';                       $candy_antecedent->tx_antecedent_category = 2;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Apnea del Sueño';                     $candy_antecedent->tx_antecedent_category = 2;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Arritmia';                            $candy_antecedent->tx_antecedent_category = 2;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Artrosis';       $candy_antecedent->tx_antecedent_category = 2;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Asma';       $candy_antecedent->tx_antecedent_category = 2;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Astigmatismo';       $candy_antecedent->tx_antecedent_category = 2;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Miopía';       $candy_antecedent->tx_antecedent_category = 2;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Bulimia';       $candy_antecedent->tx_antecedent_category = 2;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Cancer de Cuello';       $candy_antecedent->tx_antecedent_category = 2;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Cancer de Colon';       $candy_antecedent->tx_antecedent_category = 2;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Cancer de Utero';       $candy_antecedent->tx_antecedent_category = 2;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Cancer de Higado';       $candy_antecedent->tx_antecedent_category = 2;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Cancer de Laringe';       $candy_antecedent->tx_antecedent_category = 2;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Cancer de Mama';       $candy_antecedent->tx_antecedent_category = 2;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Cancer de Ovario';       $candy_antecedent->tx_antecedent_category = 2;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Cancer de Pancrea';       $candy_antecedent->tx_antecedent_category = 2;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Cancer de Pene';       $candy_antecedent->tx_antecedent_category = 2;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Cancer de Piel';       $candy_antecedent->tx_antecedent_category = 2;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Cancer de Prostata';       $candy_antecedent->tx_antecedent_category = 2;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Cancer de Pulmon';       $candy_antecedent->tx_antecedent_category = 2;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Cancer de Riñon';       $candy_antecedent->tx_antecedent_category = 2;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Cancer de Testículo';       $candy_antecedent->tx_antecedent_category = 2;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Cancer de Tiroides';       $candy_antecedent->tx_antecedent_category = 2;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Cancer de Vejiga';       $candy_antecedent->tx_antecedent_category = 2;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Cancer Oral';       $candy_antecedent->tx_antecedent_category = 2;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Cancer Oseo';       $candy_antecedent->tx_antecedent_category = 2;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Chikungunya';       $candy_antecedent->tx_antecedent_category = 2;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Dengue';       $candy_antecedent->tx_antecedent_category = 2;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Diabetes';       $candy_antecedent->tx_antecedent_category = 2;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Diabetes Gestacional';       $candy_antecedent->tx_antecedent_category = 2;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Diabetes Insipida';       $candy_antecedent->tx_antecedent_category = 2;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Enfermedad de Crohn';       $candy_antecedent->tx_antecedent_category = 2;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Epilepsia';       $candy_antecedent->tx_antecedent_category = 2;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'EPOC';       $candy_antecedent->tx_antecedent_category = 2;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Escoliosis';       $candy_antecedent->tx_antecedent_category = 2;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Sifósis';       $candy_antecedent->tx_antecedent_category = 2;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Fiebre Amarilla';       $candy_antecedent->tx_antecedent_category = 2;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Fractura';       $candy_antecedent->tx_antecedent_category = 2;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Gastritis';       $candy_antecedent->tx_antecedent_category = 2;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Gonorrea';       $candy_antecedent->tx_antecedent_category = 2;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Hemofilía';       $candy_antecedent->tx_antecedent_category = 2;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Hemorroides';       $candy_antecedent->tx_antecedent_category = 2;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Herpes';       $candy_antecedent->tx_antecedent_category = 2;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Hipertensión Arterial';       $candy_antecedent->tx_antecedent_category = 2;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Hipertiroidismo';       $candy_antecedent->tx_antecedent_category = 2;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Hipotiroidismo';       $candy_antecedent->tx_antecedent_category = 2;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Lupus';       $candy_antecedent->tx_antecedent_category = 2;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Menopausia';       $candy_antecedent->tx_antecedent_category = 2;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Microcefalia';       $candy_antecedent->tx_antecedent_category = 2;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Migraña';       $candy_antecedent->tx_antecedent_category = 2;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Miopía';       $candy_antecedent->tx_antecedent_category = 2;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Narcolepsia';       $candy_antecedent->tx_antecedent_category = 2;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Parotiditis';       $candy_antecedent->tx_antecedent_category = 2;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Pie de Atleta';       $candy_antecedent->tx_antecedent_category = 2;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Poliomelitis';       $candy_antecedent->tx_antecedent_category = 2;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Sarampión';       $candy_antecedent->tx_antecedent_category = 2;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Viruela';       $candy_antecedent->tx_antecedent_category = 2;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Prediabetes';       $candy_antecedent->tx_antecedent_category = 2;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Quemaduras';       $candy_antecedent->tx_antecedent_category = 2;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Rabia';       $candy_antecedent->tx_antecedent_category = 2;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Alergia a Penicilina';       $candy_antecedent->tx_antecedent_category = 2;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Alergia Medicamentosa';       $candy_antecedent->tx_antecedent_category = 2;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Alergia a Mariscos';       $candy_antecedent->tx_antecedent_category = 2;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Sindrome Tunel Carpiano';       $candy_antecedent->tx_antecedent_category = 2;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Varices';       $candy_antecedent->tx_antecedent_category = 2;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'ECV';       $candy_antecedent->tx_antecedent_category = 2;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Nacido Pretermino';       $candy_antecedent->tx_antecedent_category = 2;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Nacido Postermino';       $candy_antecedent->tx_antecedent_category = 2;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Rubeola';       $candy_antecedent->tx_antecedent_category = 2;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Dismenorrea';       $candy_antecedent->tx_antecedent_category = 2;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Estreñimiento';       $candy_antecedent->tx_antecedent_category = 2;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Parto Pretermino';       $candy_antecedent->tx_antecedent_category = 2;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Parto Postermino';       $candy_antecedent->tx_antecedent_category = 2;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Cesarea';       $candy_antecedent->tx_antecedent_category = 3;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Prostatectomía';       $candy_antecedent->tx_antecedent_category = 3;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Nefrectomía';       $candy_antecedent->tx_antecedent_category = 3;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Histerectomía';       $candy_antecedent->tx_antecedent_category = 3;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Apendicectomía';       $candy_antecedent->tx_antecedent_category = 3;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Artroplastía';       $candy_antecedent->tx_antecedent_category = 3;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Queratoplastía';       $candy_antecedent->tx_antecedent_category = 3;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Tiroidectomía';       $candy_antecedent->tx_antecedent_category = 3;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Transplante de Piel';       $candy_antecedent->tx_antecedent_category = 3;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Varicocelectomía';       $candy_antecedent->tx_antecedent_category = 3;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Mastectomía';       $candy_antecedent->tx_antecedent_category = 3;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'By-Pass Coronario';       $candy_antecedent->tx_antecedent_category = 3;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Colecistectomía';       $candy_antecedent->tx_antecedent_category = 3;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Vasectomía';       $candy_antecedent->tx_antecedent_category = 3;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Prostatectomía';       $candy_antecedent->tx_antecedent_category = 3;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Artroscopía';       $candy_antecedent->tx_antecedent_category = 3;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'By-Pass Gastrico';       $candy_antecedent->tx_antecedent_category = 3;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Hemorroidectomía';       $candy_antecedent->tx_antecedent_category = 3;
        $candy_antecedent->save();
        $candy_antecedent = new candy_antecedent; $candy_antecedent->antecedent_ai_medic_id = 0; $candy_antecedent->tx_antecedent_status = 1; $candy_antecedent->created_at = time(); $candy_antecedent->updated_at = time();
        $candy_antecedent->tx_antecedent_value = 'Angioplastía';       $candy_antecedent->tx_antecedent_category = 3;
    }
}
